name: Finale
main: com.github.maxopoly.finale.Finale
author: Maxopoly
version: 2.0.0-SNAPSHOT
depend: [CivModCore, ProtocolLib]
softdepend: [CombatTagPlus]
api-version: 1.17
permissions:
    finale.op:
        default: op
    finale.cps:
        default: op
    finale.cmv:
        default: op
